# JPA
spring:
  jpa:
  properties:
  hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  ddl-auto: update
  # MySql
  datasource:
    #url: jdbc:mysql://localhost/spring-security-form-login
    #url: jdbc:mysql://localhost:3306/datacard?useSSL=false
    #username: root
    #password: root
    url: jdbc:mysql://10.14.31.172:3306/datacard?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: kuser
    password: Ku5er
    # Connection Pool
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true





